Class {
	#name : #GtRrEnvironment,
	#superclass : #Object,
	#instVars : [
		'scheduler'
	],
	#category : #'RemoteRunner-Runner'
}

{ #category : #accessing }
GtRrEnvironment >> scheduler [

	^ scheduler
]

{ #category : #accessing }
GtRrEnvironment >> scheduler: anObject [

	scheduler := anObject
]

{ #category : #'startup - shutdown' }
GtRrEnvironment >> start [

	
]

{ #category : #'startup - shutdown' }
GtRrEnvironment >> stop [

	
]
