Class {
	#name : #GtRrPrePostTaskAction,
	#superclass : #Object,
	#category : #'RemoteRunner-PrePostTaskActions'
}

{ #category : #actions }
GtRrPrePostTaskAction >> postTaskAction: aGtRrTask [
	"Default is to do nothing.
	Subclasses should override as required."
]

{ #category : #actions }
GtRrPrePostTaskAction >> preTaskAction: aGtRrTask [
	"Default is to do nothing.
	Subclasses should override as required."
]
