Class {
	#name : #GtRrExampleResultWithTask,
	#superclass : #Object,
	#instVars : [
		'exampleResult',
		'task'
	],
	#category : #'RemoteRunner-UI'
}

{ #category : #accessing }
GtRrExampleResultWithTask >> exampleResult [

	^ exampleResult
]

{ #category : #accessing }
GtRrExampleResultWithTask >> exampleResult: anObject [

	exampleResult := anObject
]

{ #category : #accessing }
GtRrExampleResultWithTask >> task [

	^ task
]

{ #category : #accessing }
GtRrExampleResultWithTask >> task: anObject [

	task := anObject
]
